spring:
  application:
    name: grpc-example-user-service-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
grpc:
  # gRPC 服务器配置，对应 GrpcServerProperties 配置类
  server:
    # gRPC Server 随机端口
    port: 0
server:
  # Web服务器随机端口
  port: 0
