spring:
  application:
    name: grpc-example-user-service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
grpc:
  client:
    grpc-example-user-service-provider:
      negotiation-type: plaintext
