spring:
  application:
    name: apollo-example
server:
  port: 9090
app:
  id: ${spring.application.name}
apollo:
  meta: http://localhost:8080
  bootstrap:
    enabled: true # 是否开启 Apollo 配置预加载功能。默认为 false。
    eagerLoad:
      enable: true # 是否开启 Apollo 支持日志级别的加载时机。默认为 false。
    namespaces: application # 使用的 Apollo 的命名空间，默认为 application。
