spring:
  application:
    name: mybatis-plus
  datasource:
    url: jdbc:mysql://localhost:3306/plus_test
    username: root
    password: my-secret-pw
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
