spring:
  application:
    name: hystrix-web-service
server:
  port: 18080
management:
  endpoints:
    web:
      exposure:
        # 需要开放的端口；通过设置 * ，可以开放所有端点
        include:
          - health
          - info
      # Actuator 提供的 API 接口的根目录。默认为 /actuator
      base-path: /actuator
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
