spring:
  session:
    store-type: redis
    redis:
      namespace: ss
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 10s
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 1
        # 连接池最大的阻塞时间
        max-wait: 10s
