spring:
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  freemarker:
    settings:
      tag_syntax: auto_detect
      template_update_delay: 2
      default_encoding: UTF-8
      output_encoding: UTF-8
      locale: zh_CN
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.###
      classic_compatible: true
    template-loader-path:
      - classpath:/templates/
    suffix: .ftlh
    charset: UTF-8
    content-type: text/html
    check-template-location: true
