spring:
  application:
    name: spring-security-jdbc-login
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL;
  sql:
    init:
      platform: h2
  h2:
    console:
      enabled: false
